### ISSUE TITLE
stream freezing when ads are played - firefox

### ISSUE THREAD

**Issue by CameronJHall** [saucettv/VideoAdBlockForTwitch#30] opened 2022-02-13 03:33 UTC
It's hard to tell if it happens every time or just some times but I'm getting an issue where the stream freezes when an ad plays during midroll ads. It doesn't go back to normal until I refresh the page or the video player. I've tried enabling and disabling the FFZ plugin and it happens either way. I do have other adblock plugins installed (privacy badger and ublock) but nothing specific to twitch except ffz.

Let me know if I can do anything to collect more info.

**Comment by serenadezzz** [comment] 2022-02-14 01:54
Same here, sometimes the image freeze but not the audio

**Comment by garbb** [comment] 2022-02-14 19:27
I have occasionally experienced the same issue. Video image freezes but audio plays normally.

**Comment by saucettv** [comment] 2022-02-14 22:03
Thank you all for the reports. I have also noticed this issue with some streamers. If possible, please let me know some streams that it happens on, then we can work out if it's due to some kind of codec or if Twitch is testing something new on a select number of streamers.

**Comment by saucettv** [comment] 2022-02-17 17:18
This is for sure a Firefox only issue. I think it has something to do with the player not liking going from 30fps to 60fps automatically. As an example, I can set the player to 480p and the issue does not happen, but if I set it to 720p60, it freezes as the script attempts to go from 480p to 720p60, when an ad shows.

This doesn't happen on Chrome and Twitch seems to be using the same player script for both. I'm guessing it's something that has been changed in Firefox. It's going to need a little more research or some kind of quick hack around to fix it.

**Comment by saucettv** [comment] 2022-02-19 01:49
Thank you, I've been trying a few workarounds but haven't got a fix just yet. I know what I need to do now though hopefully, as all the other methods failed. Will hopefully have a fix by early next week if all goes well.

**Comment by l-gthb** [comment] 2022-02-19 14:22
this happens even at lower quality. for example right now i'm watchin a stream at 160p (but pretty sure 360p does the same) and it is freezing on *almost* every midroll ad.
i don't know why it doesn't freeze every single time, maybe because sometimes i have the stream on an inactive tab? not sure it can be this and i also think that the freezes happen "randomly" even when the stream is constantly in PiP mode.

worth noting i'm not actually using this extension, but the notify-strip script (with tampermonkey), but i don't think it should be different. correct me if i'm wrong.

i know all these informations are quite approximate, but unfortunately i haven't done some proper testing because i was sure the cause was Twitch itself, until now.

**Comment by saucettv** [comment] 2022-02-19 15:29
> this happens even at lower quality. for example right now i'm watchin a stream at 160p (but pretty sure 360p does the same) and it is freezing on _almost_ every midroll ad. i don't know why it doesn't freeze every single time, maybe because sometimes i have the stream on an inactive tab? not sure it can be this and i also think that the freezes happen "randomly" even when the stream is constantly in PiP mode.
> 
> worth noting i'm not actually using this extension, but the notify-strip script (with tampermonkey), but i don't think it should be different. correct me if i'm wrong.
> 
> i know all these informations are quite approximate, but unfortunately i haven't done some proper testing because i was sure the cause was Twitch itself, until now.

The notify-strip script is very different to the logic in this extension, so I can't really compare as although they are similar, the code logic is too different.

**Comment by saucettv** [comment] 2022-02-19 15:33
I have just updated Firefox to version 5.2.7. What happens now is the extension forces the player to think it's switched quality just before the ad starts and also then does the same when the ad finishes. As I didn't notice the issue when using 480p quality, only the other qualities, I'm hoping this works.

It needs testing on mid-rolls, so I'm going to leave this issue open, until there is more feedback. Please be aware this only applies to this extension, not the notify-strip script, if you want to try this one, please make sure notify-strip is disabled, or vice versa.

Thanks!

**Comment by albertopasqualetto** [comment] 2022-02-19 15:56
It's happening the same with me in Edge (not sure if when there should be ads)

**Comment by saucettv** [comment] 2022-02-19 19:01
If it does end up moving to Chrome and this Firefox update works, I will just transfer the code over, just need some feedback first from the Firefox users.

**Comment by saucettv** [comment] 2022-02-19 22:02
Ok I can see this happening on Chrome now. I'm pushing the update to all versions in 5.3.0. I have tested it a few times with pre-rolls and mid-rolls and it seems to work, Sometimes the player controls bug, but it's nothing big. Will close the issue, but feel free to open a new one if there is any more problems.

**Closed by saucettv** 2022-02-19 22:02 UTC

**Comment by albertopasqualetto** [comment] 2022-03-12 15:32
It is still freezing for me, but at this point I think it was freezing also without the extension.
