### ISSUE TITLE
Stream delay in new background tabs

### ISSUE THREAD

**Issue by Jeddix** [saucettv/VideoAdBlockForTwitch#14] opened 2021-09-11 17:04 UTC
Normally, when I open a twitch stream in a new background tab in Firefox it doesn't play until I activate the tab and then the stream has the normal delay (1-2 seconds).

When using this extension streams in new background tabs already start to buffer when the tab is openend. So when I switch to the tab after e.g. 20 seconds I have 20 seconds delay on the stream.

**Comment by saucettv** [comment] 2021-09-11 17:54
Hi, thank you for reporting. I have reproduced it and fixed it in version 5.0.3. The script will now do a fast pause/play when switching to the new tab to correct the delay. Firefox is already approved and ready to update, but Chrome is always very slow with reviewing, so that may take a few days. Thanks again

**Comment by Jeddix** [comment] 2021-09-11 18:14
I just tested it and it works BUT I don't think this is the right solution for the problem. Now EVERYTIME I switch to and from a Twitch tab I get a small pause in the stream, not just at the very first time after opening the stream. So even if I switch to another tab from a stream it does the pause.

This e.g. interferes with the BTTV setting where I don't let the stream on the Twitch start page play. Your extension starts the promoted stream after switching from the tab with the start page.

**Comment by saucettv** [comment] 2021-09-11 19:39
This is the problem, we either have it so that Twitch can automatically stop streams when an ad tries to show and the tab is hidden (Users who like to listen while doing other stuff in different tabs get annoyed by this), or do it the current way with the short pause/play. Twitch uses the browser tab visibilitystate to determine whether to stop the stream or not, if it's hidden, they will, so we force it to be visible and it's unknown when exactly they check each time, but then without the pause/play we will get the stream delay on new background tabs.

So I have to weigh up the number of users who are more likely to have multiple streams playing at the same time in multiple tabs, compared to the users who listen to one stream in the background while in different tabs and a short pause/play is better overall as the amount of people listening/switching to multiple playing streams at the same time should be fairly low and for less time.

You could change your Firefox settings to prevent autoplay globally, go to Firefox settings, then search for autoplay and choose "block audio and video", that should then stop the homepage from auto-playing and also background tabs from starting automatically.

It's all a bit of a pain but it's all workarounds because of the ads.

**Comment by Jeddix** [comment] 2021-09-11 20:37
Maybe make this new behaviour optional. In the current state I'd rather have the initial delay than the pause everytime.

And please don't see this as complaining, I'm happy that your extension at least offers a workaround for ads :).

**Comment by saucettv** [comment] 2021-09-11 20:42
No not at all, all feedback helps me :) will have a think and see if I can come up with something better

**Comment by saucettv** [comment] 2021-09-11 22:13
Re-opening this as pausing/resuming causes issues with vods/clips. Need to find a different way to correct the delay issue.

**Comment by saucettv** [comment] 2021-09-18 13:36
This should now be fixed in 2b1c318c54864a2c0ea09700288171173f878161

Uploading to Firefox/Chrome now.

**Closed** 2021-09-18 13:39 UTC

**Comment by Jeddix** [comment] 2021-09-19 09:29
I just did a quick test and it looks good now.

**Comment by saucettv** [comment] 2021-09-19 10:28
Thanks for letting me know 👍
