### ISSUE TITLE
Bug when blocking the ad causes stream to freeze

### ISSUE THREAD

**Issue by DavidBrazSan** [saucettv/VideoAdBlockForTwitch#2] opened 2021-06-13 21:23 UTC
When the extensive locks the ad, it changes the resolution to 1080p and freezes the image and only listens to the audio. After it blocks back the resolution I chose and everything is normal.

**Comment by saucettv** [comment] 2021-06-14 10:19
Hi, If you normally use a video quality less than 1080p, click on the extension icon, or go to the extensions page in your browser, find the extension and click on options. Then turn off the "Try for 1080p ad-free stream" toggle. Refresh the Twitch page and try again. This should fix your issue, if not, let me know. Thanks

**Comment by DavidBrazSan** [comment] 2021-06-14 12:32
I watch at 480p and don't use that option.

**Comment by saucettv** [comment] 2021-06-16 09:48
So just to confirm, your extension settings, look ike this?:

[https://imgur.com/o9NAiZV](url)

Also, is this problem on Chrome or Firefox? Just need this info so that I can test it and try to reproduce the bug.

**Comment by DavidBrazSan** [comment] 2021-06-16 23:31
My configuration is the same as this one. And it happens in both Chrome and Firefox.

**Comment by saucettv** [comment] 2021-06-18 17:52
Hi, if it is all un-checked, the ad blocker won't work at all, as the first option turns it off. You need to at least keep the first option on. Then make sure you refresh the page. I have a feeling this may be some kind of conflict with another script. Do you have any other Twitch specific ad blockers running? Like TTV LoL or Purple AdBlock, or any userscripts running if installed via uBlock or Tamper Monkey etc?

I have tested this issue, but I am unable to reproduce it on either browser.

Thanks

**Comment by DavidBrazSan** [comment] 2021-06-19 13:56
What I wanted to say is that I use the same setting as your image. I'm using a translator so what I wanted to say was wrong.

**Comment by DavidBrazSan** [comment] 2021-06-19 13:57
I disable the other blockers and don't use script.

**Comment by saucettv** [comment] 2021-06-19 14:09
No problem. I can't reproduce this bug currently, but I will keep this issue open in case other users also have the problem. Please check you don't have any other Twitch based ad-blockers or userscripts installed though.

**Comment by DavidBrazSan** [comment] 2021-06-19 14:25
I use the latest Firefox.
I leave the transmission in 480p, when it blocks the ad, it changes the resolution to 1080p, it keeps loading the image but the audio comes out normally.
After blocking back to normal.

**Comment by saucettv** [comment] 2021-06-19 15:20
I think that maybe the extension settings are not saving to the browser. When I changed the extension setting to 480p only, I had to close all Twitch tabs and then refresh them. Have you tried closing the Twitch tabs and restarting the browser?

**Comment by saucettv** [comment] 2021-06-20 12:13
I have re-uploaded my original extension which basically limits the player to 480p always, but is ad-free. It's on Firefox https://addons.mozilla.org/en-US/firefox/addon/ad-free-but-480p-for-twitch/ , waiting for Chrome approval. This one might suit you better, until I can find a fix for this issue.

**Comment by saucettv** [comment] 2021-06-23 15:51
Chrome link if you need it: https://chrome.google.com/webstore/detail/ad-free-but-480p-for-twit/kdicfccgckkckdkcbilhbeacnnkcmpeb

**Comment by saucettv** [comment] 2021-06-25 13:00
I'm going to close this issue as the problem should be fixed in the upcoming 4.4 version.

**Closed by saucettv** 2021-06-25 13:01 UTC
